# https://github.com/DavidAnson/markdownlint-cli2

config:
  default: true

  # Ignore
  MD007: false  # Unordered list indentation
  MD013: false  # Line length
  MD025: false  # Multiple top-level headings (TODO: enable this?)
  MD030: false  # Spaces after list markers
  MD033: false  # Inline HTML
  MD049:
    style: underscore

globs:
  - "docs/**/*.md"
  - "!site/**"
