# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#
# https://zensical.org/docs/get-started/

# Project information
site_name: CVEalert.io Documentation
site_url: https://docs.cvealert.io
site_author: Kamil Vavra
site_description: >-
  CVEalert.io helps you stay ahead of security vulnerabilities by monitoring, alerting,
  and managing CVEs in real time. Built for developers, teams, and security professionals.

# Repository
repo_name: cvealert/docs
repo_url: https://github.com/cvealert/docs
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright &copy; 2025 CVEalert.io

# Configuration
theme:
  name: material
  language: en
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
  palette:
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  favicon: assets/logo.webp
  logo: assets/logo.webp
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - privacy
  - search
  # - i18n:
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #         build: true
  #       - locale: cs
  #         name: Czech
  #         build: true
  #         nav_translations:
  #           Getting Started: Začínáme
  #           Overview: Přehled
  #           Registration: Registrace
  #     docs_structure: folder

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/cvealert
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cvealert/
      name: LinkedIn
    - icon: fontawesome/solid/battery-three-quarters
      link: https://stats.uptimerobot.com/CKfINonKI7
      name: Stagus Page
    - icon: fontawesome/solid/envelope
      link: mailto:info@cvealert.io
      name: Email address
  alternate:
    - name: English
      link: /
      lang: en
    # - name: Czech
    #   link: /cs/
    #   lang: cs

# Page tree
nav:
  - Getting Started:
      - Overview: index.md
      - Registration: registration.md
      - Login: login.md
      - First Steps: first-steps.md
      - FAQ: faq.md
  - Application: 
      - Dashboard: app/dashboard.md
      - Alerts: app/alerts.md
      - CVE detail: app/cve.md
  - Software:
      - Monitoring: software/monitoring.md
      - Catalog: software/catalog.md
      - Search: software/search.md
      - CVEs: software/cves.md
      - Featured: software/featured.md
  - Settings:
      - Projects: settings/projects.md
      # - Projects:
      #     - Project Overview: projects/index.md
      #     - Invite Users: projects/invite.md
      #     - Roles & Permissions: projects/roles.md
      - Webhooks: settings/webhooks.md
      - User Settings: settings/user.md
      - Logs: settings/logs.md
      - Two-Factor Auth: settings/2fa.md
  # - API Reference:
  #     - Overview: api/index.md
  #     - Swagger: api/swagger.md
