# https://github.com/squidfunk/mkdocs-material

name: Documentation

on:
  # push:
  #   branches:
  #     - main
  pull_request: {}
  workflow_dispatch: {}

permissions: {}

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mkdocs
        run: |
          mkdocs --version
