# https://github.com/squidfunk/mkdocs-material

name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions: {}

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mkdocs
        run: |
          mkdocs --version

      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force
