# https://github.com/DavidAnson/markdownlint-cli2-action
# https://github.com/DavidAnson/markdownlint-cli2

name: Lint - Markdown

on:
  pull_request:
    paths:
      - 'docs/**/*.md'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-slim
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
        with:
          config: '.markdownlint-cli2.yaml'
          globs: |
            docs/**/*.md
            !site/**
