# https://github.com/woodruffw/zizmor

name: Security

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: {}

jobs:
  zizmor:
    # name: zizmor latest via PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.10.4

      - name: Install Zizmor
        run: pip install zizmor

      - name: Run Zizmor
        run: zizmor .github/workflows
